/**
 * NOTE: This class is auto generated by  Generator
 * https://github.com/Tools/-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"
#include "NFTApi.h"

#include "NFTInfo.h"

namespace stratis {
namespace nft {

/* Gets NFT item info
 *
 * Multiple status values can be provided with comma separated strings
 */
class TAPPYCHICKEN_API NFTApi::GetNFTInfoRequest : public Request {
public:
  virtual ~GetNFTInfoRequest() {}
  void SetupHttpRequest(const FHttpRequestRef &HttpRequest) const final;
  FString ComputePath() const final;

  FString NFTInfoPath;
};

class TAPPYCHICKEN_API NFTApi::GetNFTInfoResponse : public Response {
public:
  virtual ~GetNFTInfoResponse() {}
  void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
  bool FromJson(const TSharedPtr<FJsonValue> &JsonValue) final;

  NFTInfo Content;
};

} // namespace nft
} // namespace stratis
