/**
 * NOTE: This class is auto generated by  Generator
 * https://github.com/Tools/-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"

namespace stratis {
namespace nft {

/*
 * NFTInfoAttributes
 *
 *
 */
class TAPPYCHICKEN_API NFTInfoAttributes : public Model {
public:
  virtual ~NFTInfoAttributes() {}
  bool FromJson(const TSharedPtr<FJsonValue> &JsonValue) final;
  void WriteJson(JsonWriter &Writer) const final;

  TOptional<FString> TraitType;
  TOptional<FString> Value;
  TOptional<FString> DisplayType;
};

} // namespace nft
} // namespace stratis
